import { ShapeOptions } from "../../../states"

export const figureList = [
  {
    type: "Circle",
    radius: 30,
    x: 30,
    y: 30,
    fill: "red",
    stroke: "black",
    strokeWidth: 1,
  },
  {
    type: "Rect",
    x: 20,
    y: 20,
    width: 100,
    height: 50,
    fill: "green",
    stroke: "black",
    strokeWidth: 1,
  },
  {
    type: "Ellipse",
    x: 40,
    y: 40,
    radiusX: 40,
    radiusY: 30,
    fill: "blue",
    stroke: "black",
    strokeWidth: 1,
  },
  // {
  //   attrs: {
  //     x: 400,
  //     y: 300,
  //     radius: 70,
  //     angle: 60,
  //     fill: "red",
  //     stroke: "black",
  //     strokeWidth: 4,
  //     rotation: -120,
  //     draggable: true,
  //   },
  //   className: "Wedge",
  // },
  // {
  //   attrs: {
  //     x: 400,
  //     y: 300,
  //     numPoints: 6,
  //     innerRadius: 40,
  //     outerRadius: 70,
  //     fill: "yellow",
  //     stroke: "black",
  //     strokeWidth: 4,
  //     draggable: true,
  //   },
  //   className: "Star",
  // },
  // {
  //   attrs: {
  //     x: 400,
  //     y: 15,
  //     text: "Simple Text",
  //     fontSize: 30,
  //     fontFamily: "Calibri",
  //     fill: "green",
  //     draggable: true,
  //   },
  //   className: "Text",
  // },
] as ShapeOptions[]
